name: Fullstack CI/CD

on:
  push:
    branches: ["main", "production"]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Debug secrets presence
        run: |
          echo "USER_SET=${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "TOKEN_SET=${{ secrets.DOCKERHUB_TOKEN != '' }}"

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rikkei-frontend:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/rikkei-frontend:latest

      - name: Build & Push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rikkei-backend:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/rikkei-backend:latest

      - name: Deploy to production server via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: latest
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ secrets.SERVER_APP_DIR }}
            cd ${{ secrets.SERVER_APP_DIR }}
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            export IMAGE_TAG=$IMAGE_TAG
            export POSTGRES_USER=$POSTGRES_USER
            export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            docker compose pull
            docker compose up -d
            docker image prune -f